// exampleservice.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: example/api/exampleservice.proto

package exampleservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxtRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TxtRequest) Reset() {
	*x = TxtRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_api_exampleservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxtRequest) ProtoMessage() {}

func (x *TxtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_api_exampleservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxtRequest.ProtoReflect.Descriptor instead.
func (*TxtRequest) Descriptor() ([]byte, []int) {
	return file_example_api_exampleservice_proto_rawDescGZIP(), []int{0}
}

func (x *TxtRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TxtResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number uint32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *TxtResponse) Reset() {
	*x = TxtResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_api_exampleservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxtResponse) ProtoMessage() {}

func (x *TxtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_api_exampleservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxtResponse.ProtoReflect.Descriptor instead.
func (*TxtResponse) Descriptor() ([]byte, []int) {
	return file_example_api_exampleservice_proto_rawDescGZIP(), []int{1}
}

func (x *TxtResponse) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

var File_example_api_exampleservice_proto protoreflect.FileDescriptor

var file_example_api_exampleservice_proto_rawDesc = []byte{
	0x0a, 0x20, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x20, 0x0a, 0x0a, 0x54, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x25, 0x0a, 0x0b, 0x54, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0x55, 0x0a, 0x0e, 0x45,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x33, 0x34, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_api_exampleservice_proto_rawDescOnce sync.Once
	file_example_api_exampleservice_proto_rawDescData = file_example_api_exampleservice_proto_rawDesc
)

func file_example_api_exampleservice_proto_rawDescGZIP() []byte {
	file_example_api_exampleservice_proto_rawDescOnce.Do(func() {
		file_example_api_exampleservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_api_exampleservice_proto_rawDescData)
	})
	return file_example_api_exampleservice_proto_rawDescData
}

var file_example_api_exampleservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_api_exampleservice_proto_goTypes = []any{
	(*TxtRequest)(nil),  // 0: exampleservice.TxtRequest
	(*TxtResponse)(nil), // 1: exampleservice.TxtResponse
}
var file_example_api_exampleservice_proto_depIdxs = []int32{
	0, // 0: exampleservice.ExampleService.GetLen:input_type -> exampleservice.TxtRequest
	1, // 1: exampleservice.ExampleService.GetLen:output_type -> exampleservice.TxtResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_api_exampleservice_proto_init() }
func file_example_api_exampleservice_proto_init() {
	if File_example_api_exampleservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_api_exampleservice_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TxtRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_api_exampleservice_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TxtResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_api_exampleservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_api_exampleservice_proto_goTypes,
		DependencyIndexes: file_example_api_exampleservice_proto_depIdxs,
		MessageInfos:      file_example_api_exampleservice_proto_msgTypes,
	}.Build()
	File_example_api_exampleservice_proto = out.File
	file_example_api_exampleservice_proto_rawDesc = nil
	file_example_api_exampleservice_proto_goTypes = nil
	file_example_api_exampleservice_proto_depIdxs = nil
}
